name: CI Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-checks:
    name: CI Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read # リポジトリのチェックアウトに必要
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
          fetch-depth: 2
      - name: Use Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24.x
          cache: 'npm'
      - run: npm install --frozen-lockfile
      - run: npm run build
      - run: npm run lint
      - run: npm run format:check
