name: CI Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-checks:
    name: CI Checks
    if: github.head_ref != 'changeset-release/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read # リポジトリのチェックアウトに必要
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint:ts

      - name: Check formatting
        run: npm run format:check

      - name: Markdownlint
        run: npm run lint:md

      - name: Textlint
        run: npm run lint:text
