name: Deploy API Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Node.jsセットアップ
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.x
          cache: npm

      - name: 依存パッケージのインストール
        run: npm ci

      - name: ドキュメント生成
        run: npm run docs

      - name: Pages用アーティファクトのアップロード
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: docs-dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # GitHub Pagesへのデプロイに必要
      id-token: write # OIDCトークンの取得に必要
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: GitHub Pagesにデプロイ
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
